/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurboRouteImport } from './routes/turbo'
import { Route as SimuladoRouteImport } from './routes/simulado'
import { Route as PsicotecnicoRouteImport } from './routes/psicotecnico'
import { Route as PlacasRouteImport } from './routes/placas'
import { Route as MaisCaemRouteImport } from './routes/mais-caem'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaIdRouteImport } from './routes/biblioteca.$id'

const TurboRoute = TurboRouteImport.update({
  id: '/turbo',
  path: '/turbo',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladoRoute = SimuladoRouteImport.update({
  id: '/simulado',
  path: '/simulado',
  getParentRoute: () => rootRouteImport,
} as any)
const PsicotecnicoRoute = PsicotecnicoRouteImport.update({
  id: '/psicotecnico',
  path: '/psicotecnico',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacasRoute = PlacasRouteImport.update({
  id: '/placas',
  path: '/placas',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisCaemRoute = MaisCaemRouteImport.update({
  id: '/mais-caem',
  path: '/mais-caem',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIdRoute = BibliotecaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BibliotecaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/conquistas': typeof ConquistasRoute
  '/mais-caem': typeof MaisCaemRoute
  '/placas': typeof PlacasRoute
  '/psicotecnico': typeof PsicotecnicoRoute
  '/simulado': typeof SimuladoRoute
  '/turbo': typeof TurboRoute
  '/biblioteca/$id': typeof BibliotecaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/conquistas': typeof ConquistasRoute
  '/mais-caem': typeof MaisCaemRoute
  '/placas': typeof PlacasRoute
  '/psicotecnico': typeof PsicotecnicoRoute
  '/simulado': typeof SimuladoRoute
  '/turbo': typeof TurboRoute
  '/biblioteca/$id': typeof BibliotecaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/conquistas': typeof ConquistasRoute
  '/mais-caem': typeof MaisCaemRoute
  '/placas': typeof PlacasRoute
  '/psicotecnico': typeof PsicotecnicoRoute
  '/simulado': typeof SimuladoRoute
  '/turbo': typeof TurboRoute
  '/biblioteca/$id': typeof BibliotecaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/biblioteca'
    | '/conquistas'
    | '/mais-caem'
    | '/placas'
    | '/psicotecnico'
    | '/simulado'
    | '/turbo'
    | '/biblioteca/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/biblioteca'
    | '/conquistas'
    | '/mais-caem'
    | '/placas'
    | '/psicotecnico'
    | '/simulado'
    | '/turbo'
    | '/biblioteca/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/biblioteca'
    | '/conquistas'
    | '/mais-caem'
    | '/placas'
    | '/psicotecnico'
    | '/simulado'
    | '/turbo'
    | '/biblioteca/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  ConquistasRoute: typeof ConquistasRoute
  MaisCaemRoute: typeof MaisCaemRoute
  PlacasRoute: typeof PlacasRoute
  PsicotecnicoRoute: typeof PsicotecnicoRoute
  SimuladoRoute: typeof SimuladoRoute
  TurboRoute: typeof TurboRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turbo': {
      id: '/turbo'
      path: '/turbo'
      fullPath: '/turbo'
      preLoaderRoute: typeof TurboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulado': {
      id: '/simulado'
      path: '/simulado'
      fullPath: '/simulado'
      preLoaderRoute: typeof SimuladoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psicotecnico': {
      id: '/psicotecnico'
      path: '/psicotecnico'
      fullPath: '/psicotecnico'
      preLoaderRoute: typeof PsicotecnicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placas': {
      id: '/placas'
      path: '/placas'
      fullPath: '/placas'
      preLoaderRoute: typeof PlacasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais-caem': {
      id: '/mais-caem'
      path: '/mais-caem'
      fullPath: '/mais-caem'
      preLoaderRoute: typeof MaisCaemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/$id': {
      id: '/biblioteca/$id'
      path: '/$id'
      fullPath: '/biblioteca/$id'
      preLoaderRoute: typeof BibliotecaIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
  }
}

interface BibliotecaRouteChildren {
  BibliotecaIdRoute: typeof BibliotecaIdRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaIdRoute: BibliotecaIdRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  ConquistasRoute: ConquistasRoute,
  MaisCaemRoute: MaisCaemRoute,
  PlacasRoute: PlacasRoute,
  PsicotecnicoRoute: PsicotecnicoRoute,
  SimuladoRoute: SimuladoRoute,
  TurboRoute: TurboRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
